tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle' # To be able to use run `brew bundle` to install all apps - https://medium.com/@satorusasozaki/automate-mac-os-x-configuration-by-using-brewfile-58a78ce5cc53


brew 'awscli'
brew 'aws-cdk'
brew 'background-music'
brew 'cookiecutter'
brew 'databricks'
brew 'fd'
brew 'go'
brew 'jesseduffield/lazygit/lazygit'
brew 'jq'
brew 'luarocks'
brew 'neovim'
brew 'nvm'
brew 'pnpm'
brew 'prettier'
# brew 'pyenv'
brew 'ripgrep'
brew 'rover'
brew 'rust'
brew 'rust-analyzer'
brew 'starship'
brew 'uv'
brew 'wget'
# brew 'zsh-autosuggestions'
# brew 'zsh-syntax-highlighting'

cask 'alacritty'
cask 'kitty'
cask 'obsidian'
cask 'rectangle'
cask 'soundsource'
cask 'spotify'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'postman'
cask 'betterdisplay'
cask 'wezterm'
cask 'docker'
cask 'docker-compose'
