tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle' # To be able to use run `brew bundle` to install all apps - https://medium.com/@satorusasozaki/automate-mac-os-x-configuration-by-using-brewfile-58a78ce5cc53


brew 'aws-cli'
brew 'aws-cdk'
brew 'go'
brew 'luarocks'
brew 'neovim'
brew 'nvm'
brew 'ripgrep'
brew 'rust'
brew 'rye'
brew 'wget'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'alacritty'
cask 'kitty'
cask 'obsidian'
cask 'rectangle'
cask 'soundsource'
cask 'spotify'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'postman'
cask 'betterdisplay'
cask 'wezterm'
cask 'docker'
cask 'docker-compose'
