backend = "glx";
#vsync = true;
#detect-rounded-corners = true;
#detect-client-opacity = false;
#refresh-rate = 60;
#detect-transient = true;
#detect-client-leader = false;
#use-damage = true;
#log-level = "warn";
#glx-no-stencil = false;
#glx-copy-from-front = false;

corner-radius = 8

shadow = false;
shadow-radius = 25;
shadow-offset-x = -20;
shadow-offset-y = -15;
shadow-red = .1
shadow-exclude = [
  "name = 'Rofi'"
];

